### PR TITLE
ESLint with AirBnb Sytle Guide

### PR DESCRIPTION
**Pull request by fabrv**
* I changed the 4 vars with consts
* Changed everything with airbnb rules

### CODE REVIEW

**Comment by mtliendo** [comment]
Renaming this since the PR to update `var` to `const` was just merged.  @fabrv Do you mind pulling in the latest changes and pushing them up?

**Comment by fabrv** [comment]
> Renaming this since the PR to update `var` to `const` was just merged. @fabrv Do you mind pulling in the latest changes and pushing them up?

Nope, somebody beat me to it :((. I didn't realize it was already PRed.

**Comment by fabrv** [comment]
Done, my dude, merged and without conflicts. :)))

**Comment by mtliendo** [comment]
LGTM, thanks again for your contribution.

**Pull request merged**
